spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://poststeadfrontend:4200"
            allowed-headers: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      httpserver:
        wiretap: false
      httpclient:
        wiretap: false
        connect-timeout: 300000
        response-timeout: 10000s
      routes:
        - id: userservice
          uri: http://userservice:8081
          predicates:
            - Path=/api/users/**
        - id: postservice
          uri: http://postservice:8082
          predicates:
            - Path=/api/posts/**
  jackson:
    serialization:
      write-dates-as-timestamps: false
      fail-on-empty-beans: false
