spring:
  application:
    name: poststead-gateway-service
  cloud:
    gateway:
      routes:
        - id: postSteadUsers
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**
        - id: postSteadPosts
          uri: http://localhost:8082
          predicates:
            - Path=/api/posts/**

server:
  port: 8080
